### ISSUE TITLE
Display unread messages in groups in dock icon like in Slack

### ISSUE THREAD

**Issue by MrGluek** [overtake/telegram#104]
Display unread messages in dock icon like in Slack - unread messages in groups as dot, unread private messages or mentions with number.

![2015-04-27 19 59 01](https://cloud.githubusercontent.com/assets/11082640/7352879/e6b990ac-ed17-11e4-866d-40103e59e57e.png)

**Comment by overtake** [comment]
we working at grouping unread messages. Thanks for idea.
