### ISSUE TITLE
[MAJOR] Self-destruct timer broken in secret chats

### ISSUE THREAD

**Issue by ialexryan** [overtake/telegram#105]
When I activate the self-destruct timer in a secret chat that I created, my send messages expire and disappear after the expected amount of time, but the received messages from the other person persist indefinitely (even if I go to another chat and come back) until I quit and reopen the app.

Can someone reproduce this?

This seems very important since it affects one of the more security-focused features of the application.

**Comment by overtake** [comment]
sorry about this. i fixed this and application now waiting for review.

**Comment by ialexryan** [comment]
Fantastic, thank you very much for fixing it quickly.
