### ISSUE TITLE
Crash loop after trying to create a secret chat

### ISSUE THREAD

**Issue by trahma** [overtake/telegram#109]
While attempting to create a secret chat, Telegram crashed and whenever starting the application again, it crashes right after it shows my contacts list.   Crashing results regardless of choosing "Don't Reopen" or "Reopen" when trying to restart Telegram.

Link to debug report: https://gist.github.com/trahma/66eac545aaed3fd68107

**Comment by michaelahlers** [comment]
:+1:

**Comment by zsm1703** [comment]
same issue here.

**Comment by overtake** [comment]
@trahma 
wtf, i can't reply this. can you send me all files with 'yap' prefix from ~/Library/Application support/telegram/database for fix this.

write me please to telegram @vihor

**Comment by zsm1703** [comment]
@overtake MAS version.

**Comment by overtake** [comment]
@zsm1703 try to find yap_store files in finder?

**Comment by luminshi** [comment]
@overtake I have the same issue as well. It goes to the loop once I initiate the secure chat on my osx client. However, if someone else create the chat, it was okay.

**Comment by rschmukler** [comment]
Just chiming in that I also have this issue.

**Comment by overtake** [comment]
i fixed this in beta. Sorry guys.  ;((

try use beta.

https://rink.hockeyapp.net/apps/c55f5e74ae5d0ad254df29f71a1b5f0e

**Comment by rschmukler** [comment]
@overtake thanks!!
