### ISSUE TITLE
No contacts or conversations are shown

### ISSUE THREAD

**Issue by imran0** [overtake/telegram#110]
I have recently updated to Version 1.55.19460, I have noticed that after updating all my contacts and conversations have disappeared. 

However I am still logged into my account as I can still see my number and username present. The conversations and contacts are still visible in my other Telegram clients (iOS App)

![image](https://cloud.githubusercontent.com/assets/6119505/7551164/325b2c98-f676-11e4-88c0-949844be0e01.png)

![image](https://cloud.githubusercontent.com/assets/6119505/7551165/35cf6e3e-f676-11e4-9a4b-00a216e7db9d.png)

**Comment by ronilaukkarinen** [comment]
I have the same issue, exactly after the update to 1.55.19460.

**Comment by tOverney** [comment]
Yup, same thing! I switched to tdesktop for now!

**Comment by overtake** [comment]
ok guys, i find bug. try new beta or use appstore version

**Comment by ronilaukkarinen** [comment]
Yep, it works now. Thanks.
