### ISSUE TITLE
Buggy handling of existing URLs

### ISSUE THREAD

**Issue by hatarist** [overtake/telegram#112]
For example, I paste (or write it myself) a URL - "http://github.com/" - into the message.

If we try to edit that URL somehow (like, replace a text in the middle of it or append a subdomain or whatever else, after the first symbol the cursor goes to the end of the URL so it becomes inconvenient to edit the existing URLs.

In this example I try and select "github" in a given URL and replace it with "bitbucket" instead. No success - after writing a "b" the cursor goes to the end of the URL and the "itbucket" goes there too. :)

GIF:
![telegram-url-bug](https://cloud.githubusercontent.com/assets/2741725/7554160/bc48d1bc-f725-11e4-8d78-78d3358d1b5b.gif)

It happens on both stable (from App Store) and beta versions of Telegram (this, specifically, is 1.55.19424 on OS X 10.10.3) for now.

Thanks in advance!

**Comment by overtake** [comment]
fixed
