### ISSUE TITLE
Telegram crashes on startup v1.60 (20263) OSX 10.10.3

### ISSUE THREAD

**Issue by chmac** [overtake/telegram#124]
Just recently upgraded to Telegram version 1.6.0. Worked fine after upgrade. Rebooted (which happens infrequently, first reboot since upgrade), now Telegram won't start. Crashes on Telegram startup. Tried moving to trash, emptying trash, reinstalling, no change.

I'll copy the apple crash report below.

Is there a safe mode startup flag, or some way to debug the issue further?

Is it possible to downgrade in the app store maybe?

```
Process:               Telegram [1023]
Path:                  /Applications/Telegram.app/Contents/MacOS/Telegram
Identifier:            ru.keepcoder.Telegram
Version:               1.60 (20263)
App Item ID:           747648890
App External ID:       812412646
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Telegram [1023]
User ID:               501

Date/Time:             2015-05-31 13:01:34.341 +0200
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        5717CB81-ADAA-247A-3E6E-FBF1980D4F91

Time Awake Since Boot: 190 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TL_userStatusOnline photo_small]: unrecognized selector sent to instance 0x610000425880'
terminating with uncaught exception of type NSException
abort() called
```

**Comment by overtake** [comment]
you using beta or release version?

**Comment by chmac** [comment]
Didn't realise there was a beta available, I'm using the app store version, `1.60`, guess that's the release version? Can I download a beta version somewhere? Happy to try that...

**Comment by chmac** [comment]
Oh, and I forgot to say in my first message, thanks for the awesome app, Telegram is great, and the OSX version is much better than the desktop one, and much more useful. :-)

**Comment by overtake** [comment]
can you find t143.sqlite file and send me via telegram. @vihor

**Comment by chmac** [comment]
Where is that file located? Can't see anything in `Application Support`, global or user, nor in the app directory itself.

**Comment by overtake** [comment]
in user application container. hm.

**Comment by chmac** [comment]
I don't have anything in `~/Library/Application Support` that looks telegram related:

```
ls -a ~/Library/Application\ Support | grep -i telegram | wc -l
       0
```

Maybe I'm misunderstanding what you mean though. I also tried the `/Applications` directory like so:

```
find /Applications/Telegram.app | grep -i sqlite | wc -l
       0
```

**Comment by overtake** [comment]
/Users/mikhailfilimonov/Library/Containers/ru.keepcoder.Telegram/Data/Library/Application Support/Telegram/database

for me its.

**Comment by chmac** [comment]
Ah yes, found it. Does it contain anything confidential? Can I send a dump of specific tables instead of the whole file? It seems to have my list of contacts and some other sensitive info in it. I'm (somewhat) familiar with the sqlite3 console, so happy dumping tables like `select * from table`.

**Comment by chmac** [comment]
I tried wiping the whole directory `~/Library/Containers/ru.keepcoder.Telegram` (I made a backup) and now Telegram also crashes, but with a different error message, and now a few seconds after startup. Here's the OSX crash reporter output.

```
Process:               Telegram [1728]
Path:                  /Applications/Telegram.app/Contents/MacOS/Telegram
Identifier:            ru.keepcoder.Telegram
Version:               1.60 (20263)
App Item ID:           747648890
App External ID:       812412646
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Telegram [1728]
User ID:               501

Date/Time:             2015-05-31 13:57:14.894 +0200
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        5717CB81-ADAA-247A-3E6E-FBF1980D4F91


Time Awake Since Boot: 3500 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007fff568e8fc8

VM Regions Near 0x7fff568e8fc8:
    MALLOC_SMALL           00007f9ba6000000-00007f9ba8000000 [ 32.0M] rw-/rwx SM=PRV  
--> STACK GUARD            00007fff530e9000-00007fff568e9000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0
    Stack                  00007fff568e9000-00007fff570e9000 [ 8192K] rw-/rwx SM=COW  thread 0
```

**Comment by chmac** [comment]
If I restore the directory from backup, I get the same error as before.

**Comment by overtake** [comment]
you need only delete t143.sqlite, also save please bad database in other folder, i try add logs for you for broken database.

**Comment by chmac** [comment]
Oh interesting. You're right. I deleted just the `t143.sqlite` file, and now Telegram starts, and is running, apparently without any issue. Great. Can you learn something useful from that file? I'm happy to send it to you if you're happy to keep it confidential. Guess it's not really important what's in it, but I like Telegram because it supports end to end encryption. :-)

**Comment by chmac** [comment]
Interesting that Telegram won't start if I delete the whole directory though. Strange. Well, now it works again, thanks a lot, I'm happy. Just let me know if you want to have a look at that file to try debugging.

**Comment by overtake** [comment]
only write me into telegram. t143.sqlite has confidential info.

**Comment by chmac** [comment]
I just started a secret chat with you. If my problem is solved, do you really want the `t143.sqlite` file? Is it useful for debugging? If it's not important, I'm happy to forget about it, my problem is fixed now! :-)

I'll close this issue, but if you do want the file to debug, let me know, either here or on telegram. I'll send it via secure message on telegram if so.

**Comment by niksmac** [comment]
How came this creates `Users/mikhailfilimonov` ?

**Comment by blurstream** [comment]
Hello, I was trying to follow this procedure but I accidentally deleted the whole folder without making a back-up. At the moment I can't find any t143.sqlite file in the path you specified. Do you have any suggestion? Thank you so much!
