### ISSUE TITLE
Crash on El Capitan Beta when writing more than two lines of text

### ISSUE THREAD

**Issue by harlanhaskins** [overtake/telegram#133]
Pretty reliably crashes every time

**Comment by zhongchaoqian** [comment]
Seem to be an OS X problem. NSTextView crashing or something like that.

**Comment by overtake** [comment]
https://rink.hockeyapp.net/apps/c55f5e74ae5d0ad254df29f71a1b5f0e

i fixed this in beta.

**Comment by DiogoAndre** [comment]
Thanks, @overtake!

**Comment by iamDecode** [comment]
I'd like to mention that this also happens on iOS 9. I couldn't find a Telegram iOS repo but it's pretty darn annoying :)

**Comment by brainlessgit** [comment]
@overtake thanks!

**Comment by rsimsek-tgm** [comment]
@overtake thank you very much, this issue has been bugging me since I installed El Capitan.
Could you possibly link the Beta Link in your ReadMe? Thanks again.
