### ISSUE TITLE
Losing Messages.

### ISSUE THREAD

**Issue by Redoubts** [overtake/telegram#137]
With Version 1.60.20263 from the App Store,

The client is losing messages sent to me, compared to my other devices.

Mobile convo:
![img_0405](https://cloud.githubusercontent.com/assets/2435101/8214017/2a701704-14db-11e5-95cc-9cf5a1a32604.jpg)

OSX App:
![screen shot 2015-06-17 at 10 24 00 am](https://cloud.githubusercontent.com/assets/2435101/8214018/2a725370-14db-11e5-824d-e49e93814ebf.png)

**Comment by Redoubts** [comment]
Killing the app and reloading it seems to recover the lost message, but it's not a good user experience to have to do that every 5 minutes to see if I lost something.

**Comment by tsailiming** [comment]
I sometimes too lose messages. Quitting and launching the app didn't help. 

I was chatting on my mobile outside and when I came home to my laptop, the messages are lost.

- My iPad at home was fine 
- Telegram web was fine too.

**Comment by Redoubts** [comment]
Uh...

**Comment by overtake** [comment]
@Redoubts M?

**Comment by overtake** [comment]
@Redoubts i think its fixed a long time ago )

**Comment by revolter** [comment]
It still happens for me quite often. Most often in groups with many (500+) unread messages. The only way I managed to get them back was by clicking on a quoted message of a reply, while the quoted messages was missing, so it scrolls to a white "page" and then loads some messages near it. It happens on the iOS and the Mac client too.

**Comment by alick** [comment]
This happens to me very often. I am using the Android app v4.0.1 , and keep finding the recently received message in a group disappearing.

My friend confirm he has the same problem. 

I think we might need to reopen the issue. @overtake

**Comment by xsfishxs** [comment]
My friend came into the same issue here.

To be more specific:
1. This issue occurred in only one of his groups.
2. He lost about 30 most recently (about 6 hours) messages in that channel. The other members in the same channel do not come into the same situation.
3. Both his macbook pro (with Sierra 10.12.6) and iPhone 6s (with iOS 11)  apps lost the messages. Reinstall the apps does not recover the issue, seems like an issue on the account?

Hope this info would help ~

**Comment by revolter** [comment]
If another user replies to one of the missing messages, and you tap the "replied to" message, the whole chunk loads.
