### ISSUE TITLE
Doesn't start after update

### ISSUE THREAD

**Issue by ronilaukkarinen** [overtake/telegram#138]
Hello. Just updated Telegram just now and it doesn't start at all.

![Telegram](http://i.imgur.com/eRzNMDu.png "Telegram")

**Comment by overtake** [comment]
https://rink.hockeyapp.net/apps/c55f5e74ae5d0ad254df29f71a1b5f0e/app_versions/549

**Comment by ronilaukkarinen** [comment]
Thanks! it works now.
