### ISSUE TITLE
Delete conversation with ⌘⌫

### ISSUE THREAD

**Issue by MarkVillacampa** [overtake/telegram#147]
As the title says, pressing ⌘⌫ should delete the current conversation.

**Comment by brainlessgit** [comment]
As far as I can see, ⌘⌫ just deletes text in input.

**Comment by MarkVillacampa** [comment]
That is the default behaviour for a NSTextField (I think). In Messages.app, if the text field has any content, ⌘⌫ deletes if. If the text field is empty, a prompt is presented to confirm the deletion of the current conversation

**Comment by brainlessgit** [comment]
@MarkVillacampa 
> If the text field is empty, a prompt is presented to confirm the deletion of the current conversation

this doesn't work for me on El Capitan and latest telegram.
But I have a question, should it work in this way?

**Comment by MarkVillacampa** [comment]
Telegram does not work in that way, Messages.app does.

I am suggesting Telegram should work this way.
