### ISSUE TITLE
An option to hide/disable stickers altogether

### ISSUE THREAD

**Issue by hatarist** [overtake/telegram#154]
It would be great, IMHO, not to see the stickers since it takes a lot of space on the screen. Also, it looks bloaty and not that meaningful like Emoji is. And it's really annoying. 
I know that it's the people I talk with, but nevertheless...

**Comment by brainlessgit** [comment]
@hatarist :+1:

**Comment by boecko** [comment]
Please let people decide in their client, if they want to see these stickers or if the just want to see emojis ...

This (Stickers) is the **most annoying feature**, i've seen for a long time.
It just takes space.

Thank you

**Comment by LukeLR** [comment]
Can't you manage the sticker packs you have subscribed to somewhere in the preferences? (Haven't my Mac with me) and then just delete all the packs, including the "Great Minds"-Pack?

**Comment by boecko** [comment]
It's not about sticker packs ... I have none ....
I don't want to see stickers, which other users are sending. Because it doesn't matter if you have this sticker pack or not, you **WILL** see the sticker.
An emoji instead is sufficient for me.

**Comment by snrnats** [comment]
I want to disable stickers too

**Comment by mrgluek** [comment]
At least you may show only emoji and display sticker on mouse hover.

**Comment by kellenp** [comment]
I have a slightly different reason - sometimes stickers are NSFW, and while normally my job would have no problem with me having a chat application open occasionally in some rooms people will post NSFW stickers. Being able to disable stickers on just my "work" client would be a very nice feature for me.

**Comment by miguelmorales85** [comment]
I need this option. Please add an option to disable in general and also in groups individually. Some get really spammy and annoying

**Comment by lorien** [comment]
Why the ticket is closed?

**Comment by jaakaappi** [comment]
@overtake how is making smaller a solution to an issue that requests disabling altogether?

**Comment by rodneyrod** [comment]
@overtake Why are you closing this? Are you trying to disengage from the community?

**Comment by Sykox** [comment]
I hate the side bar, there should be option to hide it if we dont want. @overtake please take note of this. you cant force us something we dont want.

**Comment by Ekizare** [comment]
@Sykox in latest tdesktop build you can hide a sidebar by clicking an emoji icon.
![image](https://user-images.githubusercontent.com/13734768/26975900-98f5c3c0-4d43-11e7-96d8-98fa46d57cb0.png)

**Comment by rockymontana** [comment]
@rodneyrod @lorien @sykox It was referenced and "handled" and closed because of that, I guess.

Still taking up shitloads of space though. I too want to be able to close that sidebar all together.

**Comment by jaakaappi** [comment]
In desktop client it can be closed by clicking the emoji icon next to the
text area. The point for this issue is to hide stickers from messages.

**Comment by abyss7** [comment]
An issue is unresolved - is there a new one with the same demand, or is it possible to re-open this one by community members?

**Comment by hatarist** [comment]
The developers have rewritten the macos client from scratch using Swift; AFAIK, they are tidying  up the source code for it to be opensourced soon. I'd just wait for it to be released and then try again. I'd even try to implement this myself, like I did in https://github.com/overtake/telegram/pull/260 or something.

**Comment by lorien** [comment]
I've created simple bot that removes every sticker posted to the telegram group. Someone might find it useful.
Bot: https://t.me/nosticker_bot
Github: https://github.com/lorien/nosticker_bot
