### ISSUE TITLE
Option to disable message preview in desktop notifications

### ISSUE THREAD

**Issue by jieyanhuang** [overtake/telegram#161]
Unlike the Qt version of Telegram, there is no option available in the settings to choose to disable the message preview in desktop notifications.

**Comment by doque** [comment]
+1 this would be a great addition.

**Comment by jieyanhuang** [comment]
Closing this as it has been fixed in v1.80

**Comment by LukeLR** [comment]
Thank you, that's great! It's a very good feature!
