### ISSUE TITLE
Add option for quote translation

### ISSUE THREAD

**Issue by lgladdy** [overtake/telegram#163]
It seems telegram will automatically turn ' quotes into a prettified version, but this means it's really hard to paste code to folks, so if you could add an option to stop quotes changing, that would be great.

**Comment by luckydonald** [comment]
Add <code>```</code> around your code.

![bildschirmfoto 2015-12-11 um 23 23 16](https://cloud.githubusercontent.com/assets/2737108/11757008/351f316c-a05e-11e5-8777-fcf172887e43.png)
