### ISSUE TITLE
Conversation tab resize doesnt work

### ISSUE THREAD

**Issue by oxide7** [overtake/telegram#164]
Hi,
In the latest version for max os, 1.70, there is no longer the ability to resize the left pane. This simply goes away by itself if the window is too small. That's great, but the ability to manually resize is necessary. Going back to the conversations when you have the window smaller (like when multitaksing) is inefficient and cumbersome. Please fix

**Comment by brainlessgit** [comment]
:+1:

**Comment by pyed** [comment]
I noticed that, as a temporary solution, you could use the arrow keys to go from a conversation to another, actually I find it more convenient.

**Comment by overtake** [comment]
fixed in 1.71
