### ISSUE TITLE
Crash when trying to delete single sticker

### ISSUE THREAD

**Issue by c143** [overtake/telegram#165]
Hey
I tried the Sticker Bot some days ago and added one single sticker. It isn't a set. And I can't delete it in the settings, there ist just that X. But when i press that, Telegram crashes. The Sticker doublicated, too, don't know why.

<img width="352" alt="bildschirmfoto 2015-07-22 um 22 01 20" src="https://cloud.githubusercontent.com/assets/9988714/8835888/9921c2d0-30bd-11e5-94b9-4cacbdea06ff.png">

Greetings

**Comment by overtake** [comment]
Thanks for report. i fixed this in my local source code. wait fix in next update

**Comment by c143** [comment]
Now it doesn't crash but i can't delete them either.
