### ISSUE TITLE
Dark/Night Mode

### ISSUE THREAD

**Issue by c143** [overtake/telegram#168]
Hey
I like to watch videos at night, while chatting with friends. On the lowest screen lightning the video is fine, but telegram with the white background is way too bright.

I would love a dark mode wich could be aktivated via button.

Greetings

**Comment by nikolay** [comment]
This is critical to have! And simple to implement. Honestly, the main reason I don't use Telegram is its super bright screen unsuitable for night use.

**Comment by ibrokemypie** [comment]
closed?
