### ISSUE TITLE
Options to hide/show dock icon and startup with system

### ISSUE THREAD

**Issue by astrochili** [overtake/telegram#169]
Please, add option to hide/show dock icon.
Adding "NSUIElement" key to info.plist doesn't work, it just crashes.

And good option would be to add user-friendly checkbox for autostart with system.

**Comment by astrochili** [comment]
It's closed because it's done or because it's ignored?

**Comment by overtake** [comment]
@astrochili for start with system y can use native feature in context menu on dock icon
