### ISSUE TITLE
Can't delete Sticker

### ISSUE THREAD

**Issue by c143** [overtake/telegram#170]
Hey
The problem mentioned here still exists: https://github.com/overtake/telegram/issues/165#issuecomment-124224849
I guess you didn't recieve a notification because the issue was closed, but the main problem is still there. It doesn't crash, but i can't delete these stickers. Nothing happens.

Greetings

**Comment by overtake** [comment]
can you send me video? i can't reproduce this.

**Comment by c143** [comment]
https://dl.dropboxusercontent.com/u/23477673/Telegram%20Bugreport.mov
I can send you the sticker on telegram if you want.

**Comment by c143** [comment]
I reinstalled Telegram, now they're gone. Bug isn't really fixed, but works for me.
