### ISSUE TITLE
Cannot download files

### ISSUE THREAD

**Issue by LukeLR** [overtake/telegram#173]
Hello folks,
I'm creating this issue for a bug that is bothering me since a couple of months now. I always thought that it only applies to my system, but now a friend of mine confirmed the bug on his brand new MacBook Pro Retina. Here's the problem:
Someone sent you a file on Telegram. The file gets displayed with the download arrow. You click the download arrow to actually get the file, but it doesn't start downloading. Instead, it a) just stays at 0% progress or b) the progress circle runs trough once within a second, stating that the file was downloaded, but c) no file was created in the specified download folder, or d) an empty, zero-byte-file gets created with the name of the received file.
This applies only to files, which are saved in a dedicated folder, images and voice memos are downloading fine.
I found out a workaround to fix this at least temporarily, by entering the "advanced settings"-section in the app's settings, you need to *re-*set the download-directory by clicking the drop-down-selector next to the "save documents to"-lable and choosing a folder where the downloads should be saved. This even might be the folder that was already selected. After that, downloads will work fine, but only until the application is restarted the next time. After the next launch, the fix needs to be applied again.
And yes, I am sure that a) a download destination folder is set in the settings, b) telegram has write access to that folder, and c) the internet connection is working ;) It really seems to sit in the procedure of loading the preferences after a restart of the application, the destination folder probably doesn't get set correctly. Maybe there's a fix for it?
Last but not least, I'm very impressed by your work and really like this telegram client ;) I'm using it every day continuosly, since most of my communication happens over telegram, and I prefer it over the alternative telegram client which works on all systems, not just because this client dismisses the omnipresent speech bubble optics, IMHO they get really annoying, and the space especially on wider screen is much better used when messages span over the full width and not just in a speech bubble to the left or right :+1: Keep up the great work! :wink:

**Comment by yanisl** [comment]
is there any fix fot this problem?

**Comment by rkeshmir** [comment]
I have the same problem. Perhaps this error displayed in browser console can help:

> app.js:12 Error: [MT] Bad server salt for invalid message
>     at u.processMessage (app.js:23)
>     at app.js:23
>     at s (app.js:13)
>     at app.js:13
>     at g.$eval (app.js:13)
>     at g.$digest (app.js:13)
>     at g.$apply (app.js:13)
>     at l (app.js:12)
>     at b (app.js:12)
>     at XMLHttpRequest.$.onload (app.js:12)
