### ISSUE TITLE
Lexical or Preprocessor Issue "'UIKit/UIKit.h' file not found" Anyone got a fix or even a clue.

### ISSUE THREAD

**Issue by xingjun** [overtake/telegram#178]
<img width="574" alt="2015-08-26 11 46 17" src="https://cloud.githubusercontent.com/assets/13231860/9485161/1728c2b0-4be8-11e5-95c5-483774c886f4.png">

**Comment by xingjun** [comment]
So, my question i s   i never build success with source code .help!

**Comment by xingjun** [comment]
submodule is not a tree,can't resolve it

**Comment by LukeLR** [comment]
Did you clone recursively?

**Comment by xingjun** [comment]
yes ,i try recursively ,buy only can clone sqlcipher

**Comment by LukeLR** [comment]
Are the folders "MtProtoKit", "Signals", "sqlcipher" all populated in the repositorie's main folder?

**Comment by xingjun** [comment]
$ git clone --recursive https://github.com/overtake/telegram.git
Cloning into 'telegram'...
remote: Counting objects: 16731, done.
remote: Total 16731 (delta 0), reused 0 (delta 0), pack-reused 16731
Receiving objects: 100% (16731/16731), 15.41 MiB | 4.00 KiB/s, done.
Resolving deltas: 100% (11310/11310), done.
Checking connectivity... done.
Submodule 'MtProtoKit' (https://github.com/peter-iakovlev/MtProtoKit.git) registered for path 'MtProtoKit'
Submodule 'Signals' (https://github.com/peter-iakovlev/Signals.git) registered for path 'Signals'
Submodule 'sqlcipher' (https://github.com/sqlcipher/sqlcipher.git) registered for path 'sqlcipher'
Cloning into 'MtProtoKit'...
remote: Counting objects: 633, done.
remote: Total 633 (delta 0), reused 0 (delta 0), pack-reused 633
Receiving objects: 100% (633/633), 8.38 MiB | 9.00 KiB/s, done.
Resolving deltas: 100% (364/364), done.
Checking connectivity... done.
fatal: reference is not a tree: ba67798afeec7944ef623ca195e348860ce3f45a
Cloning into 'Signals'...
remote: Counting objects: 393, done.
remote: Total 393 (delta 0), reused 0 (delta 0), pack-reused 393
Receiving objects: 100% (393/393), 87.18 KiB | 14.00 KiB/s, done.
Resolving deltas: 100% (225/225), done.
Checking connectivity... done.
fatal: reference is not a tree: 15243e33d7f595a3a062ebf6a3819e1987e66e1e
Cloning into 'sqlcipher'...
remote: Counting objects: 8292, done.
remote: Total 8292 (delta 0), reused 0 (delta 0), pack-reused 8292
Receiving objects: 100% (8292/8292), 27.30 MiB | 7.00 KiB/s, done.
Resolving deltas: 100% (4803/4803), done.
Checking connectivity... done.
Submodule path 'sqlcipher': checked out 'fafb0d05bdae394037ac495fe7261573f5f675eb'
Unable to checkout 'ba67798afeec7944ef623ca195e348860ce3f45a' in submodule path 'MtProtoKit'
Unable to checkout '15243e33d7f595a3a062ebf6a3819e1987e66e1e' in submodule path 'Signals'

**Comment by xingjun** [comment]
"MtProtoKit", "Signals" Foldes are empty,  'sqlcipher' clone successful,and I try clone 'MtProtoKi' 'Signals' on there master-branched ,copy them in ,but there are some errors.

**Comment by LukeLR** [comment]
You should try deleting the whole telegram-directory with all it’s subdirectories, and then issue a new `git clone --recursive https://github.com/overtake/telegram` <https://github.com/overtake/telegram%60>. This should download all the necessary files for your telegram client. Check if all the folders mentioned before are populated. If they are not empty, try building with XCode. In case they are, or in case building fails, try downloading the whole repository directly from the GitHub-Website by using the „Download ZIP“-Button on https://github.com/overtake/telegram <https://github.com/overtake/telegram>. Then unzip and try building, this should work.

**Comment by xingjun** [comment]
I try **delete** all content in telegram and delete telegram folder yet ,I try 'git clone --recursive https://github.com/overtake/telegram` **again** ,but it still did not work,Then I tried **download** it from Github-Website directly,But in UnZip folder, 'MtProtoKit','Signals', 'sqlcipher' are all empty,thank you, I think the problem probably is that  submodule 'MtProtoKit', "Signals" are uncommitted to their official GitHub master branch ,so git clone can't find them by SHA.If download it from GitHub Website ,submodules won't be download.
<img width="676" alt="hello" src="https://cloud.githubusercontent.com/assets/13231860/9538086/301c47b0-4d73-11e5-89df-467734a67a6f.png">

**Comment by xingjun** [comment]
when click submodules on GitHub Website ,only sqlcipher can be open .
<img width="998" alt="2015-08-28 12 29 39" src="https://cloud.githubusercontent.com/assets/13231860/9539170/83a0228c-4d80-11e5-8538-b06a6505aa67.png">

**Comment by LukeLR** [comment]
Okay, that would have been the next thing I'd have checked. The submodules refer to commits which don't exist, this happens for example when the author makes changes in the submodules, commits them, but not pushes yet, then the references in the main project will get updated, this is pushed, and yeah, the submodule commits are not yet online… So you could try downloading the latest commit of the submodule instead, this would be done by downloading the repositories as ZIP from their GitHub pages, then extract the contents in the corresponding folders in the telegram repository folder. If you are lucky, this older versions of the submodules still build with the project, if they do not, you have no other chance then waiting for the author to fix this problems

**Comment by xingjun** [comment]
yes,thanks.

**Comment by xingjun** [comment]
I am sorry for open 3 issues on same question, If someone has same question ,please see #182

**Comment by xingjun** [comment]
I am very sorry for open 3 issues on same question,now close! please see #182
