### ISSUE TITLE
Hide message preview on lockscreen

### ISSUE THREAD

**Issue by kathampy** [overtake/telegram#180]
Please add an option in Settings > Notifications like "Show message preview" for Apple's Mail and Messages apps which hide the contents of notifications. It would be cool if this could be done only for the lockscreen.

Please add this to the iOS version as well.

**Comment by rsimsek-tgm** [comment]
Please implement this, especially for secret chats this would be a welcome addition.

**Comment by overtake** [comment]
fixed
