### ISSUE TITLE
Anyone build success please help me !

### ISSUE THREAD

**Issue by xingjun** [overtake/telegram#182]
I can't build it success ,because submodule MTProtocol? &   Singnal ?,how you can build it ,clone its submodule successfully? as them do not exist !

**Comment by LukeLR** [comment]
Please. Read previous issues before posting. A quick search of "MTProto" or "Signal" in the issues section on here would have solved your issue. Check #177, #178 or many other issues on here.

**Comment by xingjun** [comment]
Can't build it ,all same problem no resolve.

**Comment by LukeLR** [comment]
Did you try the steps proposed in #177, #178

**Comment by xingjun** [comment]
Yes, I try. it didn't work.

**Comment by LukeLR** [comment]
So, why do you open three issues for the same problem? Please, stop spamming and use ONE issue for your problem. You won't be helped better if you annoy everyone with multiple posts, they will just be less people helping you.

**Comment by LukeLR** [comment]
Regarding your problem, if you tried all the steps I provided in #418, I'm not able to help you anymore. If you patched the failing download of the repo correctly with downloads of the submodules, and it still doesn't work, then there's nothing I can do for you, sorry. Maybe it's a bug in the project itself.

**Comment by xingjun** [comment]
I didn't see #418,but I saw #139 ,same problem,submodule can not be checkout ,update or download .

**Comment by LukeLR** [comment]
Okay, #418 was a typo, I meant #178. Yes, #139 seems to be the same issue, it was fixed by someone fixing the reference of the submodules. You could fork the repository and do this for yourself, too.

**Comment by xingjun** [comment]
Thanks, however ,  I don't know how to fix the reference of the submodules,just want someone  build success can give me his fork branch,please.

**Comment by LukeLR** [comment]
Okay, I did this for you right now. I created a fork, removed the broken refs to the broken submodule commits, and added the submodules back again. This is done via the command line with commands `git submodule deinit <Submodule Name>`, `git submodule add <git path>`. Furthermore, you need to remove their directories in the repository folder AND in the `.git/modules`-Folder before cloning again. But if you don't k

**Comment by xingjun** [comment]
- I clone your repo ,it did't work because some error,
-  your repo just as same as I did servals days before, I delete uncloned  submodule folders, and checkout submodules latest commit on their Master Head,It won't work at all, because the Author on telegram modify some code ,so ,the latest submodule code can't work well with Telegram.
- I am very sorry for my poor English & poor experience  at Github ,Thank your time,I learn something by conversation!
- I also know its wrong to open 3 issues on same question,I am sorry to all,I will never do it again next time ,thanks at all~
- And I will close 2 issues before.

**Comment by LukeLR** [comment]
Nothing to feel sorry for ;) At first, if it still doesn't work, then it's clearly an error in the code. Maybe the developers of this project have made some changes to the main repository and to the submodules, but didn't push the submodules afterwards (or something similiar). Then I'm sorry but there's nothing I can do for you anymore, we need to wait for the developers to check their code. You probably need to use the binaries (e.g. from the Mac AppStore) at first. But you don't need to feel sorry for your English, it's obvious that not anyone is able to speak high-level english (I wouldn't even say that I do, though), and it's fine you understood that it's better for everyone to concentrate on a single issue, but again, we don't dislike you for doing different ;) It's good that you closed the previous issues with a reference to this issue, so anyone stumbling upon this can understand what happened here. And I'll hope that someone of the developers gets to fix this soon ;)

**Comment by ryush00** [comment]
No update?

**Comment by ryush00** [comment]
#195

**Comment by sc0rp10** [comment]
@LukeLR i have cloned your fork (obviously, with --recursive option), but I can't build project with same error: "UIKit/UIKit.h file not found". Did you know how fix it?

**Comment by xingjun** [comment]
I have build it success now  https://github.com/xingjun/telegram.git
