### ISSUE TITLE
After last upgrade, no option to disable all notification

### ISSUE THREAD

**Issue by Raffo** [overtake/telegram#184]
After last upgrade (version 1.80.24883) I cannot find any option to disable all the notification for all chats, but I can only silence notification for each individual user. If I remember correctly, I was able to disable all notifications in the previous versions. Is it possible to have this functionality back? Can you also elaborate on the design decision of the new notification system?

**Comment by LukeLR** [comment]
You can disable all notifications in the OS X Preferences. Go to System Preferences > Notifications, choose Telegram from the list, and disable all kinds of notifications as you like it ;) I don't know if there was a feature in the client itself, but this works ;)

**Comment by Raffo** [comment]
Makes sense :) 
However, it was different before as I started getting notified about my messages and this was not happening before. Anyway, this solves my "issue", I'm closing it.
