### ISSUE TITLE
wrong image from another chat gets sent (!!!)

### ISSUE THREAD

**Issue by Fabbi** [overtake/telegram#185]
when I send a specific image (a screenshot I made) another image from another chat(!!) get's sent instead.

**What it looks like in the desktop app where I sent it:**
<img width="596" alt="screenshot 2015-09-10 14 05 43" src="https://cloud.githubusercontent.com/assets/2073275/9788411/e0466390-57c9-11e5-92db-adf74ab3a37c.png">

**what it looks like on the other side and other devices:**
![img_1506](https://cloud.githubusercontent.com/assets/2073275/9788464/4b2018e6-57ca-11e5-8200-27bcd8765e57.png)

Also the "correct image" gets displayed when I open up the full preview of the image, but with the ratio of the sent one..
It's always the same picture no matter whom I send the screenshot to.

This could have easily become a very unpleasant situation with another person or another image.

**Comment by AlvaroFranco** [comment]
Yeah, this problem is so annoying. I've experienced it a few times but I haven't been able to find a pattern to reproduce it…

**Comment by Fabbi** [comment]
could it be, that there happenes some kind of hash-collision?! How are the images saved!?

**Comment by gabovanlugo** [comment]
Same thing here. I've experienced it couple a couple of times as well.

**Comment by mrgluek** [comment]
+1

**Comment by arsenico13** [comment]
Guys... This is a serious issue.

+1!

Cannot find a way to reproduce it at will.

**Comment by overtake** [comment]
that fixed 2.10
