### ISSUE TITLE
Don't bump icon number for muted chats

### ISSUE THREAD

**Issue by rsimsek-tgm** [overtake/telegram#188]
You can indeed mute the notifications on every groupchat and specific contact, though every groupchat you have muted is going to bump the number of messages on the icon in the dock regardless, which seems quite pointless to me.
So please add the option to mute notifications for a specific chat entirely, as this is especially important for frequent group chat users, which would frequently get a number >100 in their dock.
Thank you for this awesome app @overtake

**Comment by jacobrichard** [comment]
I beleive #141 was the fix for this, if that suits your needs.

**Comment by rsimsek-tgm** [comment]
Sorry, I must have overlooked that issue. Thanks for the link to the corresponding issue.
