### ISSUE TITLE
Wrong Message Forwarded

### ISSUE THREAD

**Issue by KalenXI** [overtake/telegram#196]
I just attempted to forward a message from the XKCD channel to a friend of mine. But the message he got was from a private chat with a different friend months ago. This seems fairly serious if merely forwarding a message could allow someone else to get messages from an entirely unrelated chat.

This is what it looks like on my end with the message I intended to forward:
<img width="665" alt="screen shot 2015-11-02 at 8 20 09 am" src="https://cloud.githubusercontent.com/assets/700186/10882861/30bf2bcc-813c-11e5-8696-0e0ad6cf42ea.png">

And this is what my friend received:
![812738719_10872052276164751462](https://cloud.githubusercontent.com/assets/700186/10882867/34ffdd08-813c-11e5-902e-1a80b08cdefb.jpg)

**Comment by KalenXI** [comment]
This is also reproducible. Every time I forward a message from the XKCD channel to that friend they get a random message from my chat with Timothy.

**Comment by foxcatbox** [comment]
As the other side or this conversation, I can confirm this bug. 
![telegram-bug](https://cloud.githubusercontent.com/assets/15612105/10883067/c5715b2c-816f-11e5-8990-ff77ceb54cee.jpg)

**Comment by KalenXI** [comment]
This appears to be fixed as of version 1.99.33838
