### ISSUE TITLE
Add 'take screenshot' option to chat attachment menu

### ISSUE THREAD

**Issue by tsabirgaliev** [overtake/telegram#210]
It would be great to directly be able to take a screenshot from whole screen or some selected window or some area. The best UX would be to integrate existing 'Take screenshot' feature of OSX, like it is done in Preview app (Preview.app -> File -> Take screenshot -> {From window, From selection, From entire screen})

Thank you!

**Comment by 0xCD** [comment]
@tsabirgaliev 
You can use command-shift-control-3/4 shortcut to save your screenshot to the clipboard and command-v to paste it in Telegram app.

**Comment by tsabirgaliev** [comment]
@0xCD 👍 that makes sense, thank you!
