### ISSUE TITLE
Set download location to /tmp

### ISSUE THREAD

**Issue by robcalcroft** [overtake/telegram#214]
Is there a way to set the Download dir to `/tmp`, I attempted to show hidden files in Finder but the Telegram location chooser does not reflect this.

**Comment by LukeLR** [comment]
You can navigate to a folder in the Finder with the cmd + shift + G -shortcut. Try this ;)

**Comment by robcalcroft** [comment]
<3 thanks!

**Comment by LukeLR** [comment]
Did it work?

**Comment by robcalcroft** [comment]
It did :smile:

**Comment by LukeLR** [comment]
Okay, cool! Glad to help you!
