### ISSUE TITLE
iOS: Hide the badge count of unread messages in muted chats

### ISSUE THREAD

**Issue by tonysung** [overtake/telegram#224]
This is already done on desktop per https://github.com/overtake/telegram/issues/141 .

Should do the same on iOS.

**Comment by medoix** [comment]
+1

**Comment by audiocommander** [comment]
+1

**Comment by overtake** [comment]
![image](https://cloud.githubusercontent.com/assets/1260850/13334209/f6e1cba4-dc1b-11e5-95bd-08c9682302f6.png)


Please try App settings. I think you find answer here.

**Comment by overtake** [comment]
sorry guys. i'm blind :D this is repository for osx. not for ios.;)

**Comment by stepan001** [comment]
+1 for iOS

**Comment by glushchenko** [comment]
+1

**Comment by r3nya** [comment]
@overtake Hi mate! Where can I find the iOS repo? :) 

btw, it's very important feature.

**Comment by ha33an** [comment]
very bad issue
correct that

**Comment by glushchenko** [comment]
@overtake, please provide this report to iOS developers.

**Comment by audiocommander** [comment]
@r3nya: here's the iOS repo, you should report/bump there 
https://github.com/peter-iakovlev/Telegram/issues/31

though it seems that the iOS repo is outdated. You should also report a bug with a support request from inside telegram. Maybe this helps to raise awareness.
