### ISSUE TITLE
Images and files download is really slow

### ISSUE THREAD

**Issue by linkxvi** [overtake/telegram#230]
I'm on OS X 10.11.3 (15D21), Telegram Version 2.00.36666.

When people send me images or any other kind of file, the download is really slow, compared to the download from the iOS app. And the internet speed of my mac is five times the one of my iPhone.

**Comment by evgenyrodionov** [comment]
Upload is too

**Comment by therohanchawla** [comment]
+111111

**Comment by wolftrouble** [comment]
Still a serious issue for me. Mobile works fine, desktop images preview, stickers and downloads are agonizingly slow or stuck entirely, requiring reloading the app.

OSX 10.11.5, Telegram version 2.14.47289.

**Comment by SLCH** [comment]
Same here
Windows 7 Telegram v 0.9.56

**Comment by samayres1992** [comment]
Same here, images load near instantly on the iPhone app but the mac app is terribly slow. 

This has been an ongoing issue for some time now.

**Comment by overtake** [comment]
good news, guys. I Fixed this in beta, wait new 2.20 version in appstore or stable version.
