### ISSUE TITLE
Unable to compile on MacOS El Capitan

### ISSUE THREAD

**Issue by Saphrosit** [overtake/telegram#231]
I just cloned the whole project using 

`git clone --recursive https://github.com/overtake/telegram.git`

I also used 

`cd MtProtoKit/`
`git checkout master`

and 

`cd Signals/`
`git checkout master` 

to get also MtProtoKit and Signals which otherwise would be missing.
However, in trying to compile the project I first get a 

> 'SSignalKit/SSignalKit.h' file not found

error, which I simply solved adding manually the Signals folder in the `Header Search Path` of the Telegram project, but then I got a 

> 'UIKit/UIKit.h' file not found

which is included in MtProtoKit.h. 

I tried for a whole afternoon to get to a workaround but with no luck.
Can you please provide some help in compiling the whole project?

**Comment by xingjun** [comment]
Because submodules need some modify

**Comment by xingjun** [comment]
you can build it success with this forked project: https://github.com/xingjun/telegram

**Comment by Saphrosit** [comment]
Thank you very much, finally somebody that provides a working fork of telegram! Compiled flawlessly, thanks!

**Comment by winguse** [comment]
@xingjun do you know why these two modules is 404? (it looks like they are private)

**Comment by Anand60068** [comment]
Thank you very much ...
