### ISSUE TITLE
New emoji not visible on OS X telegram

### ISSUE THREAD

**Issue by djdylan2000** [overtake/telegram#234]
The new emoji show up as black icons in the telegram client for OSX. 
(I am running the latest version at this time: Version 2.01.38707)
![mac telegram screenshot](https://cloud.githubusercontent.com/assets/10861157/13345401/8f79502c-dc84-11e5-9030-fb1cca7462b0.jpg)
-----------------------
On the iOS telegram app, the emoji displays properly:
![iphone screenshot](https://cloud.githubusercontent.com/assets/10861157/13345446/d997e498-dc84-11e5-8b16-abde6665afb2.jpg)

Could someone please fix this?

**Comment by LukeLR** [comment]
Are you using OS X El Capitan?

**Comment by djdylan2000** [comment]
No, Yosemite.
Is this a problem with the OS not being up to date?

**Comment by LukeLR** [comment]
Yep, these new Emoji were introduced with OS X El Capitan 10.11.1. OS X delivers the Emoji, so applications like telegram don't have to.

**Comment by djdylan2000** [comment]
Ok. Thanks for the info, LukeLR!

**Comment by djdylan2000** [comment]
Closing issue as issue is with OS X not telegram.

**Comment by LukeLR** [comment]
You're welcome! Glad to help you! ;)
