### ISSUE TITLE
Notifications not removed after reading the conversation

### ISSUE THREAD

**Issue by woj-tek** [overtake/telegram#249]
Currently notifications from the notification sidebar (osx, on the left, where "Today" and "Notifications" are located) are not removed after opening the telegram from dock and reading the conversation. The only way is to clear all conversations or open Telegram from the notification.

There is seemingly similar issue (#246) and it may be related.

**Comment by overtake** [comment]
![image](https://cloud.githubusercontent.com/assets/1260850/14245221/74bc283e-fa68-11e5-9850-edfe5261c49d.png)

i added code for clearing. wait in 2.08 release on current week ;)

**Comment by woj-tek** [comment]
Wow! this was blazing-lightning-fast, I haven't had chance to close the tab :D

Thanks a million! :D

**Comment by woj-tek** [comment]
OK, this seems to re-appear in the latest version (Version 2.27.51100). Was working just fine and stopped a couple of days ago.
Currently notifications are not cleared neither from notification bar nor upon opening the app from dock.

**Comment by overtake** [comment]
@woj-tek i will return this feature in future. because Apple has performance bug with clearing notifications.

**Comment by woj-tek** [comment]
Ah, cool. So this is intentional.

However, I haven't noticed any performance problems on macOS Sierra with clearing notifications.

**Comment by woj-tek** [comment]
Hi, any updated on this? can we tentatively re-open this? or all the efforts are focused on Swift-based version?
What's worse - notification doesn't open particular chat anymore...

**Comment by overtake** [comment]
Hi. I focused on swift version, and this was fixed in swift. Also swift version will be available in appstore on next week

**Comment by overtake** [comment]
@woj-tek

**Comment by woj-tek** [comment]
Ah, cool. I've just tested it in 2.9 and it works (tho, 2.9 feels slower and still has a couple of bugs, for example strings in settings/stickers, but that's different issue)

**Comment by overtake** [comment]
@woj-tek 2.9 feels slower?

**Comment by woj-tek** [comment]
Yes, scrolling lists feels veeeery laggy compared to current stable release (where it's buttery smooth and very responsive)

**Comment by overtake** [comment]
what the osx version? And Mac? I'm wondering because 2.9+ swift version more smooth

**Comment by woj-tek** [comment]
macOS Sierra 10.12.3

Telegram:
Version 2.30.51438
Version 2.91.91309

(it just updated and seems to be a bit more smooth/less laggy but it's still noticeable, especially in settings)

**Comment by overtake** [comment]
i misunderstand you. what the version more laggy? @woj-tek

**Comment by woj-tek** [comment]
new version: Version 2.91.91309

**Comment by overtake** [comment]
@woj-tek impossible. can you give me more info about this? Where you found lags more then old version

**Comment by woj-tek** [comment]
Expecialy scrilling the lists (contact). It's the most visible in the settings if you make the window height as small as possible (i.e. half of the display) then scrolling is laggy/jarring (that may be a better word?)

**Comment by woj-tek** [comment]
Above was off-topic

Back to your comment:
> @woj-tek i will return this feature in future. because Apple has performance bug with clearing notifications.

It returned in the latest version but! it only clears notification when the particular chat is selected. I think it should remove notification when the message is read on other device as well (i.e. there is no unread count anymore in the application -- this works well), that is - one the unread count is updated it should also update/remove notifications.
