### ISSUE TITLE
IME failed to capture Enter key press

### ISSUE THREAD

**Issue by radaiming** [overtake/telegram#25]
Hi,

Thanks for you nice app, I'm using chinese input method, usually when I press Enter in IME, the IME will capture the Enter and input English instead of Chinese, like this, I will get "test":

![screen shot 2014-10-31 at 23 58 09](https://cloud.githubusercontent.com/assets/1522741/4863840/c6ea6b52-6117-11e4-8ae8-6315782bab73.png)

But telegram will capture the Enter, and send my message which is not finished, could you kindly fix this? Thanks a lot.

**Comment by iceboundrock** [comment]
This issue can be fixed by PR #52 , please merge it.

**Comment by overtake** [comment]
i check your poll, thanks.

**Comment by radaiming** [comment]
Looks this issue was fixed for a long time.
