### ISSUE TITLE
Cannot update name on profile

### ISSUE THREAD

**Issue by tuttiq** [overtake/telegram#254]
Hi,
I found a bug on my Telegram for Mac today (is it OK to post it here?), when you try to update your name under `Settings` -> `Edit`, change the name and click `Done`, nothing happens, the name is not updated, and if you click `Edit` again, previous name is still there as well.

If you update on another client (Android, in my case), then the Mac client UI still shows previous name, but under `Settings` -> `Edit`, the name is updated (but again, clicking `Done` does not refresh the UI).

![telegram-name-bug](https://cloud.githubusercontent.com/assets/1096046/14382454/d655f1fe-fd85-11e5-9c8e-cb38bdc7a782.gif)

**Comment by overtake** [comment]
@tuttiq Fixed in beta) update is coming soon

**Comment by tuttiq** [comment]
Awesome, thanks! :)
