### ISSUE TITLE
Please push latest changes

### ISSUE THREAD

**Issue by ReDetection** [overtake/telegram#255]
Hi. I see 2.09 version in the AppStore but only 2.01 here

**Comment by LukeLR** [comment]
This project is kind of abandoned. Telegram OS X isn't really open
source anymore, I guess... Sadly... I appreciated that so much, but
probably the developer was too busy on keeping GitHub up to date etc...

Am 15.04.2016 um 10:14 schrieb Serg:

**Comment by overtake** [comment]
@LukeLR Sorry. I try update code tomorrow

**Comment by LukeLR** [comment]
Wow! I didn't expect such a response! Thank you! It'd be great if you'd
publish the source again! I guess, many of us would be very thankful for
that! ;)

Am 15.04.2016 um 22:36 schrieb Mikhail:

**Comment by overtake** [comment]
@LukeLR Done ;)

**Comment by ReDetection** [comment]
@overtake Thanks a lot!

**Comment by LukeLR** [comment]
@overtake Yep, thanks!
