### ISSUE TITLE
App focuses on search bar when re-opening it

### ISSUE THREAD

**Issue by spaceisstrange** [overtake/telegram#266]
Hi! When I re-open the app after closing it (not ⌘+Q but simply pressing the X button), it automatically focuses on the search bar, which shows the recent searches instead of the chat list and makes me have to press "ESC" to actually show it. I don't know if I explain it right, so here's a gif:
![gif](https://cloud.githubusercontent.com/assets/6024783/15122408/4d981ea2-161f-11e6-9e3e-9dd836d964c3.gif)
(Here I close the app then re-open it again and press ESC)

I tried to search in the issues, but I couldn't find anything. Is this a bug or something we can change?

**Comment by overtake** [comment]
fixed
