### ISSUE TITLE
[Bug] Image viewer with a secondary monitor 

### ISSUE THREAD

**Issue by iPruch** [overtake/telegram#270]
Hello,

First of all, I'm on a 13-inch retina MacBook Pro, early 2015 with OS X El Capitan 10.11.5.
Since the new update (Version 2.12.46701) the image viewer started behaving in a wrong way with a secondary monitor. In my case, I have 2 monitors (the MacBook Pro retina screen and an external Full HD monitor). The MacBook's screen is the primary monitor, and the external one is secondary. If the Telegram window is in the primary screen, clicking on an image works as expected:

<img width="1280" alt="telegram without bug primary monitor" src="https://cloud.githubusercontent.com/assets/2997598/15359243/b958da9c-1d08-11e6-9e32-d45840fc81f4.png">

However, if the Telegram window is on the secondary screen, clicking on an image opens the image viewer on the primary screen and it doesn't fit the screen size:

![telegram bug secondary monitor](https://cloud.githubusercontent.com/assets/2997598/15359276/d96ba4f4-1d08-11e6-8745-92edb4e1c92f.png)
<img width="1280" alt="telegram bug primary monitor" src="https://cloud.githubusercontent.com/assets/2997598/15359279/dd823d14-1d08-11e6-9aa8-039e991368ff.png">

I haven't found any solution, so for now every time I want to open an image, I need to move the window to the primary screen first.

I hope this helps to solve the problem!

**Comment by overtake** [comment]
@iPruch Yes! i know this and fixed problem in beta. And i uploaded new version to AppStore with hotfix ;) Wait please.

**Comment by iPruch** [comment]
@overtake Wow, that was fast! Thank you!

**Comment by iPruch** [comment]
@overtake Should I close the issue then?
