### ISSUE TITLE
App is missing from the Mac App Store

### ISSUE THREAD

**Issue by duffpod** [overtake/telegram#285]
So, anything bad happened?

**Comment by overtake** [comment]
yes. Sorry. working on this

**Comment by MarkVillacampa** [comment]
Has the official telegram app for macOS switched to https://github.com/telegramdesktop/tdesktop ?

I personally prefer this one, but I would appreciate some insights into what happened there, and what will be the best way to get a precompiled version of this app going forward. (I used to download a precompiled version from Telegram.org)

Thanks.

**Comment by overtake** [comment]
@MarkVillacampa no. Apple blocked app with 'illegal content' reason. We a trying resolve the problem with Apple. Also in current or next week. this app start distribute without appstore too. (the same TDesktop)

**Comment by overtake** [comment]
checkout macos.telegram.org

**Comment by MarkVillacampa** [comment]
Great! But It says it's only available on the US Store. This could be a propagation isuse (meaning it will be available later) but just wanted to give a heads up:

![screen shot 2016-06-17 at 3 29 08 pm](https://cloud.githubusercontent.com/assets/1014118/16152107/68f34cb8-34a0-11e6-9a5d-7507031c280e.png)

**Comment by overtake** [comment]
@MarkVillacampa use stable version from macos.telegram.org. not from appstore

**Comment by ygbr** [comment]
Hi, will the app return to the App Store? Is there anything we can do to help?
