### ISSUE TITLE
App gone from the AppStore

### ISSUE THREAD

**Issue by wilk-polarny** [overtake/telegram#289]
Hi,

is there a reason why the app has been removed from the Mac App Store?
I'm stuck at version 2.13 - newer versions are only available as a direct download.
Also Telegram for macOS has been removed from my purchases and trying to open the AppStore page results in an error. ("... is not available in your local store.")

**Comment by andrew-bohr** [comment]
I can confirm that the app is nowhere to be found at least in Russian Mac App Store.

**Comment by wilk-polarny** [comment]
Oh, I'm sorry. Haven't checked already closed tickets.
The question has been already been answered in issue #285.
