### ISSUE TITLE
There's no Telegram app in Applications nor in Spotlight

### ISSUE THREAD

**Issue by iliv** [overtake/telegram#294]
This is AppStore version running on 10.8.5

After installation Telegram icon appeared in Launchpad. I was able to add drag-and-drop it to Dock but there's no Telegram in Applications folder nor in Spotlight.

**Comment by wilk-polarny** [comment]
Have you tried to wait a little until spotlight refreshes its index?
Did you try to reindex Spotlight manually?

**Comment by iliv** [comment]
Yes. For more than 10 hours.
No.

**Comment by iliv** [comment]
Alright, I've reindexed my Application folder. Didn't work. I then reindexed entire / volume manually. Didn't work either.

It appears that .app packages are located here:

```
shiny:~ iliv $ sudo find /Users/iliv/Library/Application\ Support/Telegram/ -name "Telegram.app"
/Users/iliv/Library/Application Support/Telegram//Telegram 18482/Telegram.app
/Users/iliv/Library/Application Support/Telegram//Telegram 24127/Telegram.app
/Users/iliv/Library/Application Support/Telegram//Telegram 30236/Telegram.app
/Users/iliv/Library/Application Support/Telegram//Telegram 33716/Telegram.app
/Users/iliv/Library/Application Support/Telegram//Telegram 37466/__MACOSX/Telegram.app
/Users/iliv/Library/Application Support/Telegram//Telegram 37466/Telegram.app
/Users/iliv/Library/Application Support/Telegram//Telegram 45888/Telegram.app
/Users/iliv/Library/Application Support/Telegram//Telegram 47249/Telegram.app
```

```
shiny:~ iliv $ ls /Applications/ |grep -i remind
Reminders.app
shiny:~ iliv $ ls /Applications/ |grep -i teleg
shiny:~ iliv $
```

The question is why? Do you have any control over where .app package is installed? Is this a problem with the App Store app?

**Comment by iliv** [comment]
Hm, okay, I identified that "Telegram 47249" folder holds the currently installed version of the .app package, as well as .zip archive. Relocated .app to /Applications and voila, it works (obviously). Now my question is how did it happen that it was placed in /Users/iliv/Library/Application Support/Telegram/ ?

**Comment by iliv** [comment]
Looks like there was some kind of conflict between standalone beta version and the App Store version of the app. I removed all folders such as "Telegram 18482", deleted Telegram from Launchpad and reinstalled it from the AppStore. It was installed to /Applications this time and there was nothing created under /Users/iliv/Library/Application Support/Telegram/.
