### ISSUE TITLE
Pasting a text link to a GIF file hangs application

### ISSUE THREAD

**Issue by iliv** [overtake/telegram#299]
This is App Store version 2.16.47503 running on 10.8.5

This is the link in question: http://img0.joyreactor.cc/pics/post/%D1%80%D1%8B%D0%B1%D0%B0-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%BA%D1%83%D0%BF%D0%B8-%D0%BC%D0%B5%D0%BD%D1%8F%21-%D0%B3%D0%B8%D1%84%D0%BA%D0%B8-3185670.gif

It hangs application regardless of the state of the "Autoplay GIFs" setting.

**Comment by overtake** [comment]
fixed on macos.telegram.org
