### ISSUE TITLE
Can't create a new line in the message field with Alt+Enter

### ISSUE THREAD

**Issue by hatarist** [overtake/telegram#311]
I'm using the beta build 2.17.48611

After the message field was updated (it's looking great now, by the way; thanks a lot!), I can't anymore create a new line in the message I write using an Alt+Enter hotkey. It is available with Cmd+Enter now, but I am used to pressing Alt+Enter and pressing it now sends the message :(

Could you please add backwards compatibility to create a newline using the Alt+Enter hotkey?
Thanks in advance!

**Comment by overtake** [comment]
fixed. thanks. wait new beta update.
