### ISSUE TITLE
Pasting screenshots from clipboard causes freeze in 2.16

### ISSUE THREAD

**Issue by hkrutzer** [overtake/telegram#312]
1. Take screenshot with ctrl+cmd+shift+4
2. Paste screenshot
3. Telegram freezes

I am using OSX 10.9.5, a friend is running 10.11 and says he does not have this issue.

**Comment by overtake** [comment]
@hkrutzer Update to beta please and check again

**Comment by hkrutzer** [comment]
Fix works, thanks!

**Comment by hkrutzer** [comment]
Fixed in 2.19

**Comment by overtake** [comment]
@hkrutzer 👌
