### ISSUE TITLE
Proxy for Telegram Client OSX

### ISSUE THREAD

**Issue by NickLiffen** [overtake/telegram#320]
There is no option to add a proxy on the telegram client for OSX. Running OSX El Capitan. 

Doesn't work behind corporate proxy.

**Comment by overtake** [comment]
@NickLiffen You can you system settings for proxy

**Comment by overtake** [comment]
@overtake *use

**Comment by Neodi** [comment]
Hope support proxy too.Now In China  I have to use Global Agent by shadowsocks to acess telegram,but in this way,when I visit Chines web,network speed will be so slow.

**Comment by sutra** [comment]
@Neodi You may use dsocks for workaround:

`env DSOCKS_PROXY=”127.0.0.1:1080″ dsocks.sh /Applications/Telegram.app/Contents/MacOS/Telegram >/dev/null 2>&1 &`

more detail see http://wp.me/p15JnE-gH

**Comment by Neodi** [comment]
@sutra Thank you ,but I download Telegram Desktop not mac app store version,there is a setting for socks5.

**Comment by meteormatt** [comment]
The [Telegram Desktop](1) support proxy, although not so beautiful as [Telegram](2)

[1]:https://itunes.apple.com/cn/app/telegram-desktop/id946399090
[2]:https://itunes.apple.com/cn/app/telegram/id747648890

**Comment by ParadiseDS** [comment]
To support proxy within telegram I've switched to [ Telegram Desktop](https://itunes.apple.com/cn/app/telegram-desktop/id946399090) and all things go well.

**Comment by hayorov** [comment]
More than ever, support of SOCKS5 proxy needed 😱

**Comment by overtake** [comment]
its available in beta. Wait 3.0 its will coming soon

**Comment by inke88** [comment]
More than ever, support of SOCKS5 proxy needed 😱
+1
+1
+1

**Comment by ParadiseDS** [comment]
For those who need socks5 proxy urgently Telegram Desktop is a fairly good alternative on macOS

**Comment by overtake** [comment]
@ParadiseDS Socks5 is supported in latest versions

**Comment by ParadiseDS** [comment]
> Socks5 is supported in latest versions
Happy to hear that. Nice Update!

**Comment by inke3c** [comment]
@overtake 
Login can be set sock5, I feel not friendly, you can set up before landing, but still very happy to use sock5 proxy, thank you.
