### ISSUE TITLE
"Use Large Fonts" setting not being respected in message input field

### ISSUE THREAD

**Issue by rafaelclaycon** [overtake/telegram#321]
After I was upgraded to version 2.18.48804 of Telegram for Mac, the message input field (the one used to type-in messages) doesn't have the same font size as the text of messages displayed in the chat (as it used to before the update). I use the app with the "Use Large Fonts" setting on. I think somebody just forgot to honor the font size for the text input field too.
![480d1978-5509-11e6-8f8b-a3dc99d14720](https://cloud.githubusercontent.com/assets/5100081/17589564/de9bb87a-5fab-11e6-9a9c-f80a74330aba.png)

**Comment by GitGianluc** [comment]
Issue is still there in version 2.23.50447

**Comment by overtake** [comment]
yeah. you right. will fix

**Comment by GitGianluc** [comment]
@overtake Thank you very much!

**Comment by overtake** [comment]
fixed. wait next release
