### ISSUE TITLE
Turning off sound effects does not work with OS X Sierra

### ISSUE THREAD

**Issue by samayres1992** [overtake/telegram#323]
Currently unchecking the sound effects box does not turn off notification sounds.

The only solution at the moment is putting mac on 'do not disturb'.

**Comment by MikeThomasDev** [comment]
2017 and we can't turn off notification sounds?!

**Comment by samayres1992** [comment]
There are two options 'in-app sounds' and 'sound effects', turning off in-app sounds stops the notification noises.  I guess this could be improved a little with a small description of what the option does but it's not a bug.  

Sorry I found this out a while ago but forgot to close the ticket.
