### ISSUE TITLE
mtprotokit/mtrequest.h not found   

### ISSUE THREAD

**Issue by ankitguptaiphone** [overtake/telegram#33]
switch mtprokit to unstable branch , Please explain how can i Switch  mtprokit to unstable branch , i can not find any framework with named mtprokit

**Comment by Raffo** [comment]
Could anyone provide an easy way to build the project out of the box? Instructions are not clear. Thanks.

**Comment by DRosadoYew** [comment]
I was able to build and run it by using the master branch of MtProtoKit submodule.

**Comment by Raffo** [comment]
So the Master version is now fine?

**Comment by DRosadoYew** [comment]
It worked for me. Not sure why we shouldn't use it before but at the moment the unstable branch does not include some required changes (i.e. Password support).

**Comment by overtake** [comment]
you right guys. thanks.

**Comment by AdulteTerrible** [comment]
Should MtProtoKit return to the unstable branch, here are more detailed instructions to setup the project:
1. Checkout repository:
add this repository to XCode,
Version Control > Check Out...
2. Switch MtProtoKit submodule to 'unstable' branch (XCode: Version Control > MtProtoKit(...) > Switch to Branch...)
3. Create 'Application.h' file with this content: <as current ReadMe>
4. Register your app at my.telegram.org and change the values of Application.h accordingly.
