### ISSUE TITLE
Severe Issue: Telegram permanently deletes original file when cancelling an upload

### ISSUE THREAD

**Issue by StefanDesu** [overtake/telegram#331]
Hi,

Telegram for OS X just deleted the original file of a beautiful picture I took yesterday. I wanted to post it on Instagram and started sending it to myself as a file (uncompressed), but then changed my mind and cancelled the upload. Telegram deleted the original file off my SD card. I could easily reproduce the issue by sending a file and then cancelling the upload. It does not happen if you send pictures/videos as compressed versions.

I am surprised that this never happened to anyone else.

Best and thanks for your work,
-Stefan

**Comment by overtake** [comment]
thanks you. fixed, wait release.
