### ISSUE TITLE
[Feature request] Preview sticker with full height and width of sticker before posting

### ISSUE THREAD

**Issue by pumano** [overtake/telegram#344]
Some of my sticker packs contain images with text, and It's not readable when I preview stickers in the  right corner when I want to send it. 

Improvement:
1) add settings for possibility to preview stickers (On/Off)
2) after choosing sticker -> open sticker in preview (with full image height and width) modal window with two buttons: **Send** and **Cancel**

**Comment by muRn** [comment]
Currently if you long click on any sticker it is opened in full-size. Then you can release the click and sticker won't be sent. This way you can long click on different stickers until you find the right one. Is that what you were looking for?

**Comment by pumano** [comment]
Yes, thanks!
