### ISSUE TITLE
Telegram, VTDecoderXPCService overconsume CPU resources in idle mode

### ISSUE THREAD

**Issue by iliv** [overtake/telegram#350]
Telegram Version 2.27.51100, macOS Sierra 10.12

After a night of idle waiting, no new events such as unread messages, etc., I see this:

![Screenshot](http://i.imgur.com/anBeKxT.png)

Quitting Telegram and then starting it resolves this problem. Happened more than once already. Unfortunately, I have no idea under what circumstances this problem manifests itself.  For the past 24 hours I barely used Telegram but I can't be certain as to when exactly Telegram and VTDecoderXPCService started to overconsume CPU resources.

**Comment by joemerlino** [comment]
second that.

**Comment by overtake** [comment]
what the version you using?

**Comment by joemerlino** [comment]
Still happens on latest 2.27.51120

**Comment by overtake** [comment]
very interesting.  please check, its start after playing gifs?

**Comment by iliv** [comment]
Not in my case. I can play GIF's just fine. VTDecoderXPCService doesn't seem to show up in the process list.

**Comment by iliv** [comment]
It does, however, when I view a COUB. But it behaves. No crazy CPU overconsumption.

**Comment by iliv** [comment]
Interestingly, VTDecoderXPCService remains in the process list after I close COUB viewer.  It seems to be in sleeping state (Ss)

`iliv             30491   0.0  0.2  2529344  20244   ??  Ss   11:54AM   0:01.06 /System/Library/Frameworks/VideoToolbox.framework/Versions/A/XPCServices/VTDecoderXPCService.xpc/Contents/MacOS/VTDecoderXPCService`

Just to be clear, it doesn't seem to be started/called when viewing a GIF.

**Comment by joemerlino** [comment]
Hard to determine if it's gif related or not, I saw they have a huge impact on cpu, once I send one it goes from 0.3% to 30-40 even 70% if I send more than one in a single conversation, once I switch conversation it goes back to 1%.

**Comment by overtake** [comment]
good news. i found bug and fixed. Update will be available today on macos.telegram.org

**Comment by joemerlino** [comment]
Thank you! 👍
