### ISSUE TITLE
How to close media player ?!

### ISSUE THREAD

**Issue by mojtabye** [overtake/telegram#363]
Hi There ! ,
The new media player is great ! , but how to close it completely to prevent conflict with iTunes when we are not using telegram ?! 
<img width="195" alt="screen shot 2016-11-30 at 5 04 54 pm" src="https://cloud.githubusercontent.com/assets/13944347/20754281/75f6091c-b71f-11e6-8425-861a02a3cfa1.png">

**Comment by iM4hdi** [comment]
you need to post it here:
https://github.com/telegramdesktop/tdesktop
this repo is only for Telegram MacOS
