### ISSUE TITLE
Impossible to use custom keyboard layout

### ISSUE THREAD

**Issue by wasd171** [overtake/telegram#368]
Hello!

I am using PC keyboard, thus I have created a custom Russian key layout using Ukelele. It works fine everywhere except Telegram. Trying to type with this new layout results in English symbols only

**Comment by andreiko** [comment]
Same problem here.

**Comment by overtake** [comment]
trying to reproduce

**Comment by overtake** [comment]
please send me steps for reproduce. what the typical problems you have?
@andreiko

**Comment by andreiko** [comment]
I'm using the latest versions of Mac OS Sierra and Telegram client.

Steps to reproduce:

1. Extract [keyboard layout files](https://andreiko.ru/Russian_pcm.tar.gz) to `/Libraries/Keyboard Layouts`
2. Go to `System settings -> Keyboard -> Input sources` and add the custom layout
3. Now you can use this keyboard layout in every app, but Telegram. It cannot be selected neither via keyboard shortcut nor by selecting it from the menu.

https://andreiko.ru/screencast_2017-01-16_10-49-51.mp4

This definitely worked in October 2016. I just reinstalled my system and faced the problem.

Thanks a lot for looking into this.

**Comment by overtake** [comment]
thanks. i will check this

**Comment by overtake** [comment]
ftw. I can't reproduce for me input working ;(
@andreiko

**Comment by andreiko** [comment]
While this is still weird that only Telegram is affected, I fixed the problem by logging out and logging back in into my Mac OS session after adding the new layout.
