### ISSUE TITLE
Question about macOS Telegram development status

### ISSUE THREAD

**Issue by yangshun** [overtake/telegram#378]
This isn't really an issue per se, but I guess it's the easiest way to reach out to @overtake . I realize there have been recent updates to the macOS telegram app but the Github repository hasn't been updated since 5 Aug 2016.

Is the code now made private and no longer pushed to Github?

**Comment by f0r3s1** [comment]
+1

**Comment by overtake** [comment]
Hi guys. You right. I will update source code now ;) Sorry for this.

**Comment by yangshun** [comment]
@overtake Are you open to Pull Requests? Seems like there aren't any PRs by external contributors being merged in. I would love to contribute to this project as I use Telegram for Mac on a daily basis.  I have made some small improvements on my personal fork and was wondering if you are open to merging them.

**Comment by overtake** [comment]
@yangshun What the improvements?

**Comment by yangshun** [comment]
1. Update Git submodules with the latest commit hashes
2. Update the code to use the latest `MTProto` APIs
3. Sort emojis by index of matched query rather than order they appear in `NSString+Extended.m`
4. Better Emoji autocomplete experience (use tab/shift+tab to toggle between emojis, and also select the first one by default)
5. Only show emoji hints when the query is 2 characters or more

You can view my latest fork here: https://github.com/yangshun/telegram.

If you would like me to submit each of them as separate PRs I would be glad to do so 😄

**Comment by overtake** [comment]
@yangshun Hm. Please write me to tg: @vihor
