### ISSUE TITLE
Sparkle.framework is very out of date

### ISSUE THREAD

**Issue by pornel** [overtake/telegram#387]
This app uses a very old version of Sparkle.framework, which has known vulnerabilities and bugs on macOS Sierra. Please update Sparkle to the [latest version](https://github.com/sparkle-project/Sparkle/releases).

**Comment by overtake** [comment]
updated to Sparkle-1.16.0a1

**Comment by overtake** [comment]
@pornel thanks. how you find this app? 🤔

**Comment by overtake** [comment]
and what the vulnerabilities fixed? I know's bug with checking version, where versions count > 1 its always says 'up to date'

**Comment by pornel** [comment]
I'm trying to search github for old version of Sparkle.

Security issues are here: https://sparkle-project.org/documentation/security/

**Comment by overtake** [comment]
@pornel also in producation i'm using Sparkle-1.14.0

**Comment by pornel** [comment]
ok
