### ISSUE TITLE
Safari Share Extension no longer appearing in 1.0

### ISSUE THREAD

**Issue by brhumphe** [overtake/telegram#394]
It didn't work very well before the 1.0 update, but not it is not appearing at all. Could we get that fixed?

Some more system services would be cool too.

**Comment by overtake** [comment]
@brhumphe last version of this app is 2.30 and he contains share extension

**Comment by brhumphe** [comment]
Turns out I must be running the main version of the desktop. My mistake, I'll download this version right now.
