### ISSUE TITLE
Adding an "@everyone" tag for groups

### ISSUE THREAD

**Issue by garvamel** [overtake/telegram#430]
To make sure everyone gets a notification regardless of config. Is it possible?

Thanks.

**Comment by joemerlino** [comment]
doesn't make any sense to me.

Other clients don't have this feature so it's not a design intention to make an @everyone tag.

**Comment by garvamel** [comment]
Perhaps, I didn't actually think much further on it, but I've been in the need of such feature.

**Comment by joemerlino** [comment]
I understand, but GitHub issues are not designed to make feature requests. 

Ask on social to Durov or Telegram official channels.

**Comment by garvamel** [comment]
Sorry! Can I delete this?

**Comment by joemerlino** [comment]
No worries :) you can click on [Close issue](https://i.stack.imgur.com/vRuSR.png) to delete this.
