### ISSUE TITLE
@telegraph bot does not open auth link

### ISSUE THREAD

**Issue by amurchick** [overtake/telegram#434]
Client version: 2.92 from 2017-04-04 for MacOS

When I am use bot @telegraph and click "Log in as <username> on this device" - nothing happens.
![screen shot 2017-04-07 at 17 25 10](https://cloud.githubusercontent.com/assets/1515699/24796503/65e01494-1bb7-11e7-9591-f0c6f83c43c2.png)

In Telegram Desktop App (1.0.29) all worked as designed - click on this button opens auth link in browser.

**Comment by overtake** [comment]
@amurchick thanks, its was fixed in my code, will available tomorrow on stable version and appstore

**Comment by amurchick** [comment]
In version 2.93.91729 AppStore - fixed, thank you!
