### ISSUE TITLE
Latest beta screws up UI

### ISSUE THREAD

**Issue by gattilorenz** [overtake/telegram#447]
Running 10.11.6, just installed latest Beta, the UI is foobar.

The input line is on top of conversations, and the "about" message is weird too:
![screenshot 2017-04-21 16 06 37](https://cloud.githubusercontent.com/assets/13262392/25281214/e887908e-26ac-11e7-8ac8-4a9a37b202a3.png)

**Comment by overtake** [comment]
uploading new beta, check again after 10 min ;)

**Comment by gattilorenz** [comment]
fixed, thanks!
