### ISSUE TITLE
[suggestion] Official Repo for iOS

### ISSUE THREAD

**Issue by AdulteTerrible** [overtake/telegram#45]
Hi,

could you ask the developers of Telegram's iOS client to create an official public repo? There's none so far, but for people external to the project commiting the source code provided on Telegram's website (version 1.1 I believe). I'd sleep better if I could fork from an official repo, even if it contained only 1.1!

(I know it's not related to your work on the OSX client, but I couldn't find a way to reach them directly)

Thanks!

**Comment by overtake** [comment]
Sorry! I don't know about iOS source code ;( Please ask this question to support team!

**Comment by AdulteTerrible** [comment]
Hi @overtake, thanks for your reply! Will ask the support team :)
