### ISSUE TITLE
App very slow, big lag after update 3.18.0

### ISSUE THREAD

**Issue by l3l4c7-h4t** [overtake/telegram#459]
Hi
I'm Telegram developer and after I updated my App to market, people complaining about some big lag in main Activity (dialogs List), after clicking on some dialog, fetching data from the server and almost everywhere...

is any solution to fix it?

Regard

**Comment by overtake** [comment]
which OS?

**Comment by l3l4c7-h4t** [comment]
Android

**Comment by darezik** [comment]
This is telegram for macOS. You are in the wrong github project. I recommend you close this issue.

**Comment by overtake** [comment]
@darezik 👆

**Comment by l3l4c7-h4t** [comment]
I can't find "issues page" in https://github.com/DrKLO/Telegram ... :-/
how can I report this bug for Android OS?
is very very Necessary.

Regard

**Comment by overtake** [comment]
@l3l4c7-h4t I think if you a developer, you can analyze  and debug the code and found problem by your self.
