### ISSUE TITLE
Minimum window height is too big

### ISSUE THREAD

**Issue by ialexryan** [overtake/telegram#46]
In OS X's built-in Messages.app, the minimum height the window can be shrunk down to is 340 pixels. For some reason, it seems Telegram for OS X can only be resized to a minimum height of 600 pixels. I don't see any reason it should require itself to always be at least 600 pixels tall, and in fact on small screens (such as the Macbook Air 11") it makes the app needlessly difficult to use. Hopefully this should be an easy fix :)

**Comment by overtake** [comment]
thanks, i changed min height to 300 px ;)
