### ISSUE TITLE
It would be nice to add a quick switcher like Slack app

### ISSUE THREAD

**Issue by jopereyral** [overtake/telegram#462]
Hi

It would be nice to add some sort of quick switcher like the Slack app when someone press `cmd + k`.  Just like the image below

<img width="462" alt="screen shot 2017-05-23 at 9 07 37 pm" src="https://cloud.githubusercontent.com/assets/5117647/26383995/e541f4ba-3ffb-11e7-89f6-7f9f86e05ca4.png">

**Comment by overtake** [comment]
@jopereyral its available in beta.

**Comment by woj-tek** [comment]
semi-off-topic: @overtake is there a "beta channel" (think of play store beta program) that would automatically update to the latest beta?
