### ISSUE TITLE
'Code expired' when I try to log in

### ISSUE THREAD

**Issue by chyrta** [overtake/telegram#464]
Every time I try to log in via Telegram macOS I get 'code expired' message when I type in the code from Telegram on my phone. Couldn't reproduce this problem on Telegram Desktop, it works fine there. I have correct timezone and etc, support doesn't answer me about this issue. Thanks.

**Comment by overtake** [comment]
@chyrta Please clean application folder

**Comment by chyrta** [comment]
@overtake The solution you've proposed to these guys for the issue #444 helped me to realize where is the application folder. Thank you so much 👍
