### ISSUE TITLE
2.99.2.97000 OSX instant crash

### ISSUE THREAD

**Issue by tobsn** [overtake/telegram#468]
Starting the new updated version it instantly crashes when moving mouse into the sidebar. I can move around with tab and write but once the mouse pointer hits the sidebar tabs it crashes a fraction of a second later.

http://quick.as/GY7Jub25D

**Comment by overtake** [comment]
hi, sorry about this, i sent new version to review. Its caused only MacBooks with touch bar. For now you can download version from macos.telegram.org

**Comment by tobsn** [comment]
MacBook Pro (Retina, 13-inch, Late 2013) here.

Thanks for the quick reply!

**Comment by overtake** [comment]
do you have some settings for accessibility?

**Comment by tobsn** [comment]
hmm nothing special I don't think - I have better touch tools and moom running, those are the only once altering input and default window behavior.

**Comment by overtake** [comment]
but version from site works?

**Comment by tobsn** [comment]
yes. works perfectly fine

**Comment by tobsn** [comment]
2.99.1.96967 from the website - no issues so far int he last 5 min

**Comment by overtake** [comment]
can you give me screenshot of crash?

**Comment by tobsn** [comment]
https://pastebin.com/raw/hvwDCKTJ

**Comment by michae1ho11ey** [comment]
I'm getting a similar issue. I have a MBP without a touch bar. I just updated Telegram from the App Store (2.99.2.97000 App Store) and it'll stay running as long as I don't click in the text field to send a message. I can click on the side bar, switch chats, etc. But as soon as I click in the text field to reply to an existing chat it crashes.

Here is the dump the macOS generated after the crash. https://pastebin.com/8e8nwcMB

**Comment by overtake** [comment]
[Telegram 2.zip](https://github.com/overtake/telegram/files/1056083/Telegram.2.zip)
can you check this version?

**Comment by michae1ho11ey** [comment]
@overtake That seems to have fixed the issue. I can click on chats, send messages, and even start a new chat without a crash. I didn't mention it previously, but trying to start a new chat caused it to crash as well. Do you want any logging from me running this build to verify anything?

**Comment by Revod** [comment]
I have the same problem, but I'm downloading that zip @overtake and let you know if fix the problem

**Comment by overtake** [comment]
2.99.3 just updated in AppStore, Its should be fixed

**Comment by tobsn** [comment]
Confirmed - working! Thanks! :)

**Comment by overtake** [comment]
Sorry for this, i don't know why this affected only part of users, for my macs previous versions work fine
