### ISSUE TITLE
can't choose stickers

### ISSUE THREAD

**Issue by atayson** [overtake/telegram#475]
When selecting on smile icon i'm not able to choose sticker, just updated to version 3.0.97867

**Comment by overtake** [comment]
you mean stickers recommendations?

**Comment by atayson** [comment]
I mean i can't choose any sticker of my sets, when writing a message in a chat. They just are not clickable.
![screen shot 2017-06-27 at 00 34 18](https://user-images.githubusercontent.com/16153540/27554485-6436b014-5ad0-11e7-9c4f-589c43f62f31.png)

**Comment by overtake** [comment]
10.11?

**Comment by overtake** [comment]
@atayson fixed. wait new beta

**Comment by atayson** [comment]
thanks
