### ISSUE TITLE
Is this project under development?

### ISSUE THREAD

**Issue by Borderliner** [overtake/telegram#478]
I was wondering if there are any plans for further development. The last commit was in January, and there are lots of bugs out there, and many features are missing. Telegram for macOS is awesome, and is an essential application for any macOS user. Please update it! <3

**Comment by overtake** [comment]
what the version you about?

**Comment by overtake** [comment]
objc version no longer supported. but we have the same app with  full code rewriting from scratch on swift

**Comment by Borderliner** [comment]
Is there a github repo for it?

**Comment by overtake** [comment]
its doesn't exists. But will available in next month i hope.

**Comment by Borderliner** [comment]
So where can we report issues? Is it alright if we open issues here?

**Comment by overtake** [comment]
here. And what version of app you have?

**Comment by Borderliner** [comment]
Got one from brew cask, 2.99.1.96967 Stable.

**Comment by overtake** [comment]
@Borderliner And what the features you are missing?)

**Comment by Borderliner** [comment]
This: #479
