### ISSUE TITLE
Suggestion: Consolidate Settings pages

### ISSUE THREAD

**Issue by ialexryan** [overtake/telegram#48]
At the moment there are three entirely different places in the app where you can change settings:
- the Settings tab on the left: 
![screen shot 2015-01-15 at 11 21 59 pm](https://cloud.githubusercontent.com/assets/2292782/5772807/6ad91f5c-9d0d-11e4-8f27-92080cc3871b.png)
- the Telegram > Preferences (⌘,) screen: 
![screen shot 2015-01-15 at 11 22 29 pm](https://cloud.githubusercontent.com/assets/2292782/5772818/9127576e-9d0d-11e4-87d6-8db96ff745d5.png)
- the Advanced Settings window accessed from the above screen: 
![screen shot 2015-01-15 at 11 22 41 pm](https://cloud.githubusercontent.com/assets/2292782/5772826/9e3336ee-9d0d-11e4-8fc0-583106bb9d29.png)

I think all the settings for the app should be in the same place. Having them in three different places is bound to confuse users.

**Comment by overtake** [comment]
Another window for geek settings.
