### ISSUE TITLE
Since 3.0, Telegram prevents Mac from sleeping when idle

### ISSUE THREAD

**Issue by mb3** [overtake/telegram#486]
Since 3.0, Telegram seems to always have a `PreventUserIdleSystemSleep` assertion active, as seen with `pmset -g assertions`:

```
pid 2726(Telegram): [0x0000367a00018edb] 04:02:41 PreventUserIdleSystemSleep named: "disable app nap"
```

This can also be seen by opening Activity Monitor, going to the Energy tab and looking in the "Preventing Sleep" column.

This means that when Telegram is running, the Mac will never sleep, unless the user explicitly puts it to sleep.

**Comment by overtake** [comment]
@mb3 Hm. Will fix it

**Comment by overtake** [comment]
@mb3 fixed.  fix will avaiable in the end of week

**Comment by mb3** [comment]
This works as expected in 3.1. Thanks!

**Comment by overtake** [comment]
@mb3 np. Enjoy dark mode 😉
