### ISSUE TITLE
Suggestion: Remove grey title bar

### ISSUE THREAD

**Issue by ialexryan** [overtake/telegram#49]
The design language of OS X since Yosemite no longer includes the old-fashioned grey title bar. To comply with these new design standards, the grey menu bar should be removed and the stoplight buttons moved to the space of the window below.

Telegram: 
![screen shot 2015-01-15 at 11 19 50 pm](https://cloud.githubusercontent.com/assets/2292782/5772848/1b6c9ef2-9d0e-11e4-87e7-bc69a6618714.png)

Messages.app: 
![screen shot 2015-01-15 at 11 21 49 pm](https://cloud.githubusercontent.com/assets/2292782/5772849/200d18e2-9d0e-11e4-811c-3075f06cbcf8.png)

**Comment by imran0** [comment]
+1

**Comment by kontinuity** [comment]
+1

**Comment by yadomi** [comment]
+1

**Comment by asux** [comment]
:+1:

**Comment by overtake** [comment]
yes, this goog idea, but application need full redesign for this. 

Spoiler: We are working on it ;)
