### ISSUE TITLE
Telegram crashing after trying to play youtube video

### ISSUE THREAD

**Issue by voitnib** [overtake/telegram#495]
1. Open any chat with link to youtube video
2. Click on preview/play button

> Process:               Telegram [15553]
> Path:                  /Applications/Telegram.app/Contents/MacOS/Telegram
> Identifier:            ru.keepcoder.Telegram
> Version:               3.00.1 (100200)
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           Telegram [15553]
> 
> Date/Time:             2017-07-15 00:37:58.164 +0300
> OS Version:            Mac OS X 10.12.5 (16F73)
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'
> terminating with uncaught exception of type NSException
> abort() called

**Comment by overtake** [comment]
was fixed in beta. wait release please.
