### ISSUE TITLE
Amharic fonts are shown as squares

### ISSUE THREAD

**Issue by yarons** [overtake/telegram#496]
I can't read Amharic in messages with this app.
This is how it looks on the Mac version:
<img width="741" alt="screen shot 2017-07-16 at 23 11 10" src="https://user-images.githubusercontent.com/406826/28250927-2732acfc-6a7c-11e7-823d-22f18267d1b8.png">
This is from the Android version:
![photo_2017-07-16_23-13-56](https://user-images.githubusercontent.com/406826/28250952-7b51d452-6a7c-11e7-8dfb-ecae57c82fef.jpg)

Sorry for my terrible Amharic, I'm learning.

**Comment by overtake** [comment]
it desktop app. use macos.telegram.org
