### ISSUE TITLE
Since 3.1, pressing left when in a conversation in compact view no longer returns you to your contact list

### ISSUE THREAD

**Issue by ailnlv** [overtake/telegram#498]
Issue started with today's update (2017-07-19). While inside a conversation in a narrow window (see  image), I could previously press the left arrow on the keyboard to get back to the contact list, but this is no longer the case.

![screen shot 2017-07-19 at 4 10 38 pm](https://user-images.githubusercontent.com/3317169/28387527-73fdaaaa-6c9d-11e7-89d4-086ffb86b050.png)

**Comment by overtake** [comment]
@ailnlv got it. fixed
