### ISSUE TITLE
Suggestion: Add dictionary lookup support to received message.

### ISSUE THREAD

**Issue by brynthomas** [overtake/telegram#51]
When using Telegram I miss the easy dictionary lookup that appears in many native Mac OS apps. If I hover over a word in a received message, I would hope to be able to press Cmd+Ctrl+D or three finger tap on the trackpad to see a definition.

This works in the message field for me typing outgoing messages, but I can't do the lookup for messages received.

**Comment by overtake** [comment]
you can settings this in profile
