### ISSUE TITLE
Quick Search still works after locking

### ISSUE THREAD

**Issue by hamid914** [overtake/telegram#515]
Following these steps reproduce the issue:

1. Setup Passcode in Preferences > Privacy and Security > Security > Passcode.
2. Press `⌘ + L` to lock.
3. Press `⌘ + K` to open Quick Search
Quick Search is opened and shows contacts while Telegram is locked.

**Comment by hamid914** [comment]
Persists in 3.2.104075 AppStore

**Comment by overtake** [comment]
@hamid914 will fix

**Comment by overtake** [comment]
@hamid914 fixed, thanks, will available in next release

**Comment by hamid914** [comment]
@overtake Thanks for your support, but the bug is still exists in 3.2.1.104303 AppStore.
Maybe you mean the next major release.

**Comment by overtake** [comment]
@hamid914 sorry, i forgot to merge branches

**Comment by overtake** [comment]
will be fixed in 3.2.3 today on stable version and tomorrow in store
