### ISSUE TITLE
Glitch when closing images and videos

### ISSUE THREAD

**Issue by Evilsine** [overtake/telegram#532]
There is a glitch that the window flickers when closing images and videos on High Sierra 

macOS version: 10.13 Beta (17A362a)
Telegram version: 3.2.2.104911 Stable

![2017-09-17 16_34_21](https://user-images.githubusercontent.com/13325407/30519323-210f88e2-9bc6-11e7-848e-cfeb40bd1bda.gif)

**Comment by kigastu** [comment]
Glad that I'm not the only one, but that glitch is really annoying

**Comment by novardanak** [comment]
yeap, have same problem

**Comment by overtake** [comment]
@novardanak app version? I think it was fixed in 3.2.4

**Comment by novardanak** [comment]
@overtake, yeap, glitches was in 3.2.2. Update solved problem for me. Thank you.
