### ISSUE TITLE
Telegram tries to connect to remote SMTP port

### ISSUE THREAD

**Issue by dschulz** [overtake/telegram#540]
Why does Telegram app (installed from the AppStore) needs to connect  to TCP/25 in remote hosts?

I just discovered this because the router at my home sends me a notification when something tries to access plain SMTP. I then confirmed that it was Telegram app by using `lsof`.

Is this normal?

**Comment by overtake** [comment]
we removed 25 port. wait next update please

**Comment by woj-tek** [comment]
Where is it reflected in code https://github.com/overtake/telegram/commits/master ?

**Comment by puddly** [comment]
I couldn't find any reference to port 25 in either this repository, [MtProtoKit](https://github.com/peter-iakovlev/MtProtoKit), or any public documents on Telegram's homepage.

The remote server exposing port 25 is one of the regular Telegram servers. Why is this port being used if it's undocumented? What data was being sent?

**Comment by overtake** [comment]
@puddly https://github.com/peter-iakovlev/MtProtoKit/commit/350fe50233204bad7e9bf992f038e55dc52a1e50

**Comment by puddly** [comment]
@overtake thanks, I was only looking at the latest code and didn't see that it was removed recently.
