### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by teddychan** [overtake/telegram#55]
I upgrade the telegram via itunes mac store.

Using 1.37.12074

and at the app just startup, I can poll the newest message for a second.
then it stopped and keep "connecting"

![image](https://cloud.githubusercontent.com/assets/1013507/5973213/97473f6c-a8a0-11e4-9af6-f22675145c66.png)

Tried remove the apps even with clean my app, but no luck.

I also try to login with same mac with another telegram user, same issues.

Any help?

**Comment by overtake** [comment]
i think it fixed in 1.55 appstore version
