### ISSUE TITLE
suggest emoji codes

### ISSUE THREAD

**Issue by jomo** [overtake/telegram#61]
It would be nice to have autocompletion of emoji codes, like here on GitHub:
![github screenshot](https://i.imgur.com/r8cZ8LV.png)

I found [this list](https://github.com/wooorm/gemoji/blob/master/Support.md) of emoji with their name and aliases that could be used to implement this.

The autocompletion isn't as important imo, but suggesting emoji that the user could mean (e.g. `:cool` suggests `:cool:` and `:sunglasses:` as seen above) would be very useful. This would also tell you whether an emoji exists or if you will end up sending e.g. `:funny:` as raw text instead.

Hope that made sense.

**Comment by l4u** [comment]
:+1:

**Comment by overtake** [comment]
maybe. but its geek feature

**Comment by jomo** [comment]
what's bad about that?

**Comment by overtake** [comment]
not bad,  ok, i think about this as i a time to be

**Comment by Jas2Ma** [comment]
Using the desktop-client, I don't think it's a geek feature.
I would also like the selector for stickers on desktop client.
