### ISSUE TITLE
sandboxd: Telegram deny file-write-create

### ISSUE THREAD

**Issue by antonmes** [overtake/telegram#64]
После перезапуска приложения не сохраняются принимаемые файлы если в настройках указана  директория отличная от домашней. Если выбрать эту же директорию повторно, то сохранение работает до закрытия приложения. Необходимо реализовать запрос привилегий для доступа к фс из песочницы.

sandboxd: Telegram deny file-write-create /Volumes/Data/temp/telegram downloads/123.download

**Comment by overtake** [comment]
странно, я запрашиваю доступ к записи на выбранную юзером директорию. но чет не пашет походу.

com.apple.security.files.user-selected.read-write
