### ISSUE TITLE
Forward media photo and media video = different result

### ISSUE THREAD

**Issue by noma4i** [overtake/telegram#74]
When I forward media photo it is forwarded w/o message **"Forwarder messages:"** but when I do that for media video - there appears annoying quotation indent. Since gif animation has class **`TL_messageMediaVideo`** all forwarded messages with gif will have mark of being for **"Forwarder messages:"**

Can **`TL_messageMediaVideo`** be exempt from being marked as forwarded as it is done for all other media types?

**Comment by noma4i** [comment]
Can't see commits about that issue and same problem persists.
Here goes 2 **forwarded messages**
![screen shot 2015-05-01 at 7 33 06 pm](https://cloud.githubusercontent.com/assets/210667/7428738/0a0f6a44-f039-11e4-89af-4ea96da67bce.png)

**Comment by overtake** [comment]
ok ok ;)

https://github.com/overtake/telegram/commit/a0b38c32fa3e7828ced7b44e1f4327369b5eaf4e
