### ISSUE TITLE
[Bug] Replied answer via push notifications in single user chats

### ISSUE THREAD

**Issue by c143** [overtake/telegram#80]
If i press the reply button at a push notification on osx, it gets to a replied answer like in teamchats.

![1](https://cloud.githubusercontent.com/assets/9988714/6881372/d13345b6-d55c-11e4-88e1-e8782e9d0de9.png)
![2](https://cloud.githubusercontent.com/assets/9988714/6881371/d1317362-d55c-11e4-9ed3-3edd9988eb02.png)

I really don't want that in single user chats, its just useless. And even in teamchats, please remove it. I don't want to answer on a specific message via that feature, i just want to write without opening telegram. Thats what this quick reply feature is for. People get confused when i write that way.

Also: Just notices, that if i press enter, the message gets sent, if i press the button, the push notification just goes away but doesn't send.

**Comment by wlcx** [comment]
+1 for this, or at least to make it a configurable option

**Comment by overtake** [comment]
sorry guys, i disabled this feature for private chats. Option now enabled only in group chats.

**Comment by c143** [comment]
Now the messages won't send at all.
