### ISSUE TITLE
Suggestion: Code highlighting

### ISSUE THREAD

**Issue by SAGV** [overtake/telegram#82]
Add `code tags` (aka code highlighting) like hipchat does:
![2015-03-31 14-30-47 image 933x187](https://cloud.githubusercontent.com/assets/2170509/6917991/8e5faf10-d7b2-11e4-87be-4466c23481fd.png)

Or like in [github markdown](https://guides.github.com/features/mastering-markdown/)
![2015-03-31 14-31-21 mastering markdown github guides](https://cloud.githubusercontent.com/assets/2170509/6918001/a2ac3dda-d7b2-11e4-9662-033dadfa6d46.png)

**Comment by asux** [comment]
+:100: Oh, it will be very cool feature which extends Telegram usage not just for mostly personal messages but work chats.

**Comment by ialexryan** [comment]
As far as I understand this is unlikely to be implemented, because Telegram is cross-platform and such a feature would require every single app for every single platform to be updated to support this syntax, and the protocol itself would have to be updated to support it.

In any case, this is the wrong forum for such a suggestion. The developer of the Mac desktop app doesn't have the ability to make this change.

**Comment by SAGV** [comment]
@ialexryan why would you need to update the protocol?

Client just parses received message and if it finds ` (apostrophe)(apostrophe)(apostrophe) `, then it will display following lines in a different bg color (plus code highlighting ) until it finds ` (apostrophe)(apostrophe)(apostrophe) ` again. 

In that case we don't need any protocol modifications and other clients will just display six apostrophes plus not highlighted code which sounds like a good fallback to me.

**Comment by overtake** [comment]
sorry, now its geek feature. maybe in feature

**Comment by kostrse** [comment]
This would be GREAT to have actually!

**Comment by ialexryan** [comment]
Now that the Telegram core developers have implemented this feature in the web app and the iOS/Android apps, this is actually not just a good idea but necessary to maintain feature consistency cross-platform. @overtake this should probably be reopened :)

**Comment by asux** [comment]
@ialexryan, really? Can you put link how to use in iOS/Android  and Web?

**Comment by ialexryan** [comment]
Surround a few words with backticks or several lines of text with triple backticks.
