### ISSUE TITLE
New gTLDs are not recognized as links

### ISSUE THREAD

**Issue by yadomi** [overtake/telegram#90]
Some new gTLD which starts being used now are not considered as links (eg: [matthewmcconaughey.science](http://matthewmcconaughey.science) ) so we can't click to open the browser.

**Comment by ialexryan** [comment]
This should be an easy fix. Is there a list of all the new approved gTLD's somewhere?

**Comment by ialexryan** [comment]
This is kind of odd...I experimented with a little-known but well-established country TLD (.mw, for Malawi) and a more well-known country TLD (.es, for Spain) and got different results. I would think that shouldn't happen...see screenshot:

![screen shot 2015-04-13 at 8 14 02 pm](https://cloud.githubusercontent.com/assets/2292782/7129782/aca9031a-e219-11e4-82da-880552b69152.png)

**Comment by ialexryan** [comment]
After searching through the repository for a number of strings (".es", ".mw", ".net") and finding nothing that resembles a list of TLD's, I'd hypothesize that this app is using some sort of built-in OS API for link detection. In that case, there's not much we can do.

**Comment by overtake** [comment]
@ialexryan is right
