### ISSUE TITLE
Suggestion: Spell checking toggle in settings

### ISSUE THREAD

**Issue by andrew-kennedy** [overtake/telegram#92]
It would be nice to be able to enable OSX's built in spell checker in the message edit field. Relevant cocoa API, in case it helps: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSSpellChecker_Class/index.html#//apple_ref/occ/cl/NSSpellChecker

From a brief searching of the codebase with ag, it appears this interface isn't used anywhere. So this could end up being a decent amount of work, I'm not really sure, as I'm not familiar with OSX development.

**Comment by overtake** [comment]
you can setting spell checking in context menu of input field
