### ISSUE TITLE
Look into supporting push notifications when the app is not running

### ISSUE THREAD

**Issue by ialexryan** [overtake/telegram#93]
Because the app is distributed through the Mac App Store, it should be possible to support push notifications when the app isn't running, using the same backend infrastructure that supports push notifications on iOS. This would probably require coordination with the official Telegram people. Has this been considered in the past?

**Comment by overtake** [comment]
we think, desktop application do not need push notifications.

**Comment by ialexryan** [comment]
Why is that? That's the main thing that keeps me on iMessage, and I know many of my friends feel the same way. It's a hugely important advantage for iMessage that it can always reach me even when the app isn't running.

Could we at least make it an option? I can't emphasize enough how important this feature is.
