### ISSUE TITLE
Telegram 1.50 crash on Mac OSX 10.10.3

### ISSUE THREAD

**Issue by mattdell** [overtake/telegram#96]
Hello,

Telegram keeps crashing on me. It happened when I went to send an Emoji through the app. There was an update for Emojis in OSX 10.10.3 so I wonder if that has anything to do with it?

I've tried closing and reopening the app. I've also tried uninstalling and reinstalling. No luck with either.

Here is the crash report: https://gist.github.com/mattdell/7cfe523edf09c20235e6

Any ideas?

Thanks!

**Comment by overtake** [comment]
fixed

**Comment by dondragon2** [comment]
how is this fixed and I am still getting the issue? Overtime i open the app it crashes.

**Comment by mattdell** [comment]
No idea. I had to delete Telegram and all associated files and then reinstall.

**Comment by overtake** [comment]
@mattdell try update to 1.55 version
